### ISSUE TITLE
run in background

### ISSUE THREAD

**Issue by magaHH** [manuc66/node-hp-scan-to#237]
how can this be run in the background?

Thx!

**Comment by manuc66** [comment]
Hi @magaHH 

You could set up an operating system service of it, or run in the start of your desktop session

**Comment by magaHH** [comment]
thx. I did the following. Maybe it helps others:

sudo vi /etc/systemd/system/hp-scan-to.service

## begin

[Unit]
Description=Node.js HP-Scan-To 
After=syslog.target network-online.target

[Service]
Type=simple
User=root
WorkingDirectory=/home/pi/node-hp-scan-to/
ExecStart=/usr/local/bin/ts-node /home/pi/node-hp-scan-to/src/index.ts
Restart=on-failure
RestartSec=10
KillMode=process

[Install]
WantedBy=multi-user.target

## end


## make the service auto-start

systemctl daemon-reload
systemctl enable hp-scan-to.service
systemctl restart hp-scan-to.service

## See what is happening
journalctl -fau hp-scan-to.service

**Comment by magaHH** [comment]
question answered
