### ISSUE TITLE
How to use on raspberry pi 4

### ISSUE THREAD

**Issue by X1pheR** [manuc66/node-hp-scan-to#402]
Would it be possible to provide a dockerfile for use on a raspberry pi 4 arm64? I tried modifying the current one but getting errors on the root and rootfs

**Comment by manuc66** [comment]
Hi @X1pheR 

Maybe you can try:
```Dockerfile
FROM arm64v8/node:alpine as build
WORKDIR /app

ADD . .
RUN yarn install -d \
 && yarn build \
 && rm dist/*.d.ts dist/*.js.map

FROM node:alpine as app
ENV NODE_ENV production
ADD root/ /

# add S6 Overlay, install shadow (for groupmod and usermod) and tzdata (for TZ env variable)
ADD https://github.com/just-containers/s6-overlay/releases/download/v2.2.0.3/s6-overlay-armhf.tar.gz /tmp/
RUN tar xzf /tmp/s6-overlay-armhf.tar.gz -C / \
 && apk add --no-cache shadow tzdata

# add builded app
WORKDIR /app
COPY --from=build /app/dist/ /app/package.json ./
RUN yarn install -d \
 && yarn cache clean --force

VOLUME ["/scan"]
ENTRYPOINT ["/init"]
CMD ["/app.sh"]
```

**Comment by charlie89** [comment]
@manuc66: There are ways to build multi-arch images for docker, so we could at least provide one for x86_64 hardware and one for arm64 hardware like a raspberry pi 4.

I own a raspberry pi 4 (running octoprint for 3d printing) and i'm thinking of converting it to docker so i can run additional services on it. That's probably happening in the next few months, then i could create a multi-arch container and test it on a raspberry pi.

Docker's buildx system [described here](https://www.docker.com/blog/multi-arch-build-and-images-the-simple-way/) seems official and easy to use, so i could write all the scripts necessary for it. I'm not completely sure but i think currently you configured a build job on [Docker Hub](https://hub.docker.com) to build the image. According to the guide it would then use a github action instead, so you would just have to disable the current build job and add a Docker Hub access token to the repository in the secrets section.

What do you think about that?

**Comment by manuc66** [comment]
@charlie89 Good proposal to have multi-arch docker images

Today image are build with : https://github.com/manuc66/node-hp-scan-to/blob/master/.travis.yml#L17 but this can be changed of course

**Comment by manuc66** [comment]
@charlie89 @clintonpower

Could you test this : https://hub.docker.com/layers/node-hp-scan-to/manuc66/node-hp-scan-to/feature-multiarch-docker/images/sha256-0e73e2283569fc098b0a9ebafdd923d777cc43a7b7cb444982c21bfdcf06d667?context=repo

**Comment by clintonpower** [comment]
@manuc66 Thank you so much for the fast update! I am receiving the following error on RPi 3B+
`node-hp-scan-to    | /command/s6-overlay-suexec: line 1: syntax error: unexpected ")"`
Am I missing something?

**Comment by manuc66** [comment]
@clintonpower Could you try again, I forgot to use the appropriate S6 according to the arch (see: https://github.com/manuc66/node-hp-scan-to/pull/513/commits/13c0fcf8653df22f5e6d63cde189f72492aa3d04)

**Comment by clintonpower** [comment]
@manuc66 it works like a charm now, thank you so much, I appreciate your work!
