### ISSUE TITLE
Scan made from ADF are corrupted

### ISSUE THREAD

**Issue by manuc66** [manuc66/node-hp-scan-to#413]
The scan from ADF (Automatic Document feed) are corrupted, images are corrupted and can't be viewed

Sample corrupted image : ![scanPage1](https://user-images.githubusercontent.com/5827164/154764138-ec980762-43f0-474e-a1be-7f666f402d6c.jpg)

If I open it in some software, it says that : `Maximum supported image dimension is 65500 pixels`

**Comment by rouvenst** [comment]
Just used the latest docker image and confirm the corrupted files when scanning via ADF. Scanning with flatbed works.
I'm using the HP OfficeJet 5740.

The Image file of one A4 page has dimensions of 1654 × 65535.
No errors in logs can be found.

[_node-hp-scan-to_logs.txt](https://github.com/manuc66/node-hp-scan-to/files/8197418/_node-hp-scan-to_logs.txt)

![scan_07 03 2022_12:34:43](https://user-images.githubusercontent.com/74061303/157028728-91b4b299-b92f-4823-9647-fa58b296f659.jpg)

**Comment by superflo22** [comment]
Tested on my HP OfficeJet 6500A, same issue there.

**Comment by autumnwalker** [comment]
Seeing the same issue here. Are issue #428 and #413 related?

**Comment by manuc66** [comment]
> Seeing the same issue here. Are issue #428 and #413 related?

@autumnwalker No I don't think it's the same issue

**Comment by BrendanErquiaga** [comment]
Seeing the same issue on my HP OfficeJet Pro 8025e

**Comment by manuc66** [comment]
The binary stream that is downloaded from the device is not corrupted during transfer.

If I use this online service, the document content can be revealed, but the height of the image is not accurate : https://jpg.repair/fix-picture.php?uid=626f9a48c4c1d4.00253158

**Comment by manuc66** [comment]
If I set the image dimension inside the JPEG stream inside the header, the picture can then be opened

I'm going to implement that fix.

**Comment by manuc66** [comment]
It's not enough to fully fix it, see #455

**Comment by manuc66** [comment]
I've analyzed the image on which size has been overridden with this online tool https://processing.compress-or-die.com/analyze-process, and it states that the file contains a DNL marker.

```The JPEG standard allows DNL markers to appear with compressed data. A DNL marker is used to define or redefine the image size within the compressed data rather than within the SOFn marker. In prac-tice DNL markers are not used and most applications cannot handle them. Therefore, we will not con-sider them further.```
https://123dok.net/article/jpeg-file-format-file-formats.y96jd0lr
