### ISSUE TITLE
Saves as .jpg instead of .pdf

### ISSUE THREAD

**Issue by superflo22** [manuc66/node-hp-scan-to#428]
My printer is HP Officejet 6500A.
Then i select save to pdf on the printer but when i look in my tmp folder there is a jpg.
The image is fine and i can open it.
[debug.log](https://github.com/manuc66/node-hp-scan-to/files/8267080/debug.log)
I am able to test this on Windows if needed

**Comment by autumnwalker** [comment]
Having the same issue with OfficeJet 6978.

**Comment by BrendanErquiaga** [comment]
Seeing the same issue on my OfficeJet Pro 8025e

**Comment by manuc66** [comment]
This has been marked as enhancement since the printer does not produce itself pdf files, if we want pdf file we have to make one in this application
