### ISSUE TITLE
Working directory for documents

### ISSUE THREAD

**Issue by autumnwalker** [manuc66/node-hp-scan-to#471]
Hello,

I'm using this in my workflow with paperless-ngx. Paperless includes a "consume" directory which watches the filesystem and triggers an ingestion when it sees a new file.

When scanning multiple pages into PDF with hp-scan-to, hp-scan-to will scan each page individually as a jpg into the scan directory and the combine them into a single PDF after the scan is complete.

Unfortunately, by having the hp-scan-to scan directory pointed to the Paperless consume directory this causes Paperless to start ingesting the individual jpg files vs. allowing hp-scan-to to complete the scan and combine into a single PDF.

Would it be possible to introduce an optional "working" directory for hp-scan-to to scan the individual files, combine, and then move to the "scan" directory?

**Comment by manuc66** [comment]
The use of a temp directory will be mandatory for temporary files, and could be configured if needed

**Comment by manuc66** [comment]
@autumnwalker could you confirm it's working ?

**Comment by autumnwalker** [comment]
Appears to work great. Thank you!!

**Comment by manuc66** [comment]
Could you send the logs ? @autumnwalker

**Comment by manuc66** [comment]
I broke the behavior with https://github.com/manuc66/node-hp-scan-to/pull/474, it should be fixed by now

**Comment by autumnwalker** [comment]
Works great! Thank you @manuc66!
