### ISSUE TITLE
Exec Format Error on RPi3B+

### ISSUE THREAD

**Issue by clintonpower** [manuc66/node-hp-scan-to#512]
I am receiving the following error in docker:

`node-hp-scan-to    | exec /init: exec format error`

I tried both, the pre-built docker container and a manual build. I assume that there is a `#!/bin/bash` missing somewhere, but cannot figure out where. 
I am running the docker container on a Raspberry Pi 3B+

**Comment by manuc66** [comment]
Hello,

The docker image is not currently supported for arm64 see https://github.com/manuc66/node-hp-scan-to/issues/402

I'm closing this issue as it's a duplicate
