### ISSUE TITLE
Support HP OfficeJet Pro 8270

### ISSUE THREAD

**Issue by KoffeinKaio** [manuc66/node-hp-scan-to#548]
Hey,

I was hoping to finally get this POS printer and paperless to work together with this - as smb scanning errors every second try.

Sadly while the new scan location appears on the printer, it is stuck at "preparing to scan" and ends after this

logs:
https://gist.github.com/KoffeinKaio/579108135ffeddf8e61cc5f51d3e73a1

Any way I can make this work?
More than happy to provide help

**Comment by manuc66** [comment]
Hello @KoffeinKaio ,

I had a look at the log provided and the device response with a http status code [409 (Conflict)](https://developer.mozilla.org/en-US/docs/web/http/status/409) when node-hp-scan-to is posting the scan job. That's the first time I see this status code in these logs.

Could you check that there is no other instance listening to the "scan" entry ? (maybe another instance has already picked the scan request - another docker container still running)

Could you also send log when run with debug flags ? (It will contain information regarding your device capabilities that may explain the behaviour)

**Comment by esackbauer** [comment]
just want to let you know that the OfficeJet 5230 printer is also working properly. 
Sorry for hijacking the thread ;)

**Comment by manuc66** [comment]
@esackbauer Thanks for the feedback !
