### ISSUE TITLE
Filename of scan looks like S31KEB~7.PDF

### ISSUE THREAD

**Issue by SimonFoag** [manuc66/node-hp-scan-to#560]
I have load the Dockercontainer in my Synology Docker App.
I set all the Variables also the PATTERN="scan"_dd.mm.yyyy_HH:MM:ss.
The Filename in the scan folder looks somthing like S31KEB~7.PDF or SOLXH4~B.PDF
I Have a HP OfficeJet 6700 Premium.
How can i solve this Problem?

Regards 
Simon

**Comment by manuc66** [comment]
@SimonFoag what was the issue ?

**Comment by SimonFoag** [comment]
I don't know why but in the windows explorer this filenames where shown as I write before. Today I looked direct in the file manager from Synology and there the names are correct. Big question mark...

**Comment by SimonFoag** [comment]
Ok,now I know the problem. The colon between the times in the pattern was the reason why the filename was showing wrong in the windows explorer.
Thanks 
Simon
