### ISSUE TITLE
Recovery after printer drops offline

### ISSUE THREAD

**Issue by phillprice** [manuc66/node-hp-scan-to#565]
Hello,

This system is great - it allows me to get documents straight into paperless-ngx from my 6950.

However if the printer is turned off and on again this system needs to re-register itself, which I do by logging in and restarting the container.

I don't know if there's a way within this container of sensing whether the printer is offline and back online, whether through a healthcheck to the management url or using an arp scan or something?

**Comment by manuc66** [comment]
@phillprice Could you try this PR:  https://github.com/manuc66/node-hp-scan-to/pull/570 ?

**Comment by phillprice** [comment]
I have tried but I see a continuous axioms error when on or off. 

I'm going to delete  my copy and try again and provide evidence here over the weekend

**Comment by manuc66** [comment]
I switched from ping to http port probing, it has higher chance to work inside docker
