### ISSUE TITLE
 Deskjet 3050 All-in-One J610a only jpg

### ISSUE THREAD

**Issue by hendrik1120** [manuc66/node-hp-scan-to#568]
Hello, first of all thank you for supporting this great project!

I just tried using this with my Deskjet 3050 All-in-One J610a and everything works very well with bonjour, but for some reason I only get jpgs and no pdfs in the output. The printer is capable of generating PDFs on its own, but in the web ui it defaults to jpg for every scan.
Are there maybe some additional settings I did miss?
I will just include the logs here since they are pretty short.

Host destinations fetched: 
New Destination registered: scan - /WalkupScan/WalkupScanDestinations/1c8530e5-b81c-1f08-8d61-984be142325d
Using: scan
Waiting scan event for: /WalkupScan/WalkupScanDestinations/1c8530e5-b81c-1f08-8d61-984be142325d
Start listening for new ScanEvent
Scan event captured, saving scan #1
Selected shortcut: SaveDocument1
ScanPlexMode is : Simplex
 
New job created: http://192.168.5.221:8080/Jobs/JobList/1
Ready to download page job page 1 at: /Scan/Jobs/1/Pages/1
Page downloaded to: /scan/scan_22.10.2022_08:53:41.jpg
Job state: Completed, totalPages: 1:
Scan of page(s) completed totalPages: 1:
	- page   1 - 1654x2338 - /scan/scan_22.10.2022_08:53:41.jpg
Running iteration: 0 - errorCount: 1
Host destinations fetched: scan
Re-using existing destination: scan - http://192.168.5.221:80/WalkupScan/WalkupScanDestinations/1c8530e5-b81c-1f08-8d61-984be142325d
Using: scan
Waiting scan event for: http://192.168.5.221:80/WalkupScan/WalkupScanDestinations/1c8530e5-b81c-1f08-8d61-984be142325d

Edit: Just to clarify, the error counter being 1 is my fault, as I disconnected the printer to see what happens. I should have redeployed the container...

**Comment by manuc66** [comment]
Hello @hendrik1120 

Can you re-run with debug option ? (-D)

It will capture the device manifest and capabilities

Thanks

**Comment by hendrik1120** [comment]
Yes, of course. Sorry I missed that in the doc.

[_node-hp-scan-to_logs.txt](https://github.com/manuc66/node-hp-scan-to/files/9845132/_node-hp-scan-to_logs.txt)

**Comment by hendrik1120** [comment]
And these are the logs after a scan is triggered:

[_node-hp-scan-to_logs_with_scan.txt](https://github.com/manuc66/node-hp-scan-to/files/9845136/_node-hp-scan-to_logs_with_scan.txt)

**Comment by hendrik1120** [comment]
I just noticed that you aren't using the pdf from the printer, but instead converting the jpg to pdf.
Was this intended?

[node-hp-scan-to_logs.txt](https://github.com/manuc66/node-hp-scan-to/files/9845374/node-hp-scan-to_logs.txt)

**Comment by manuc66** [comment]
Yes it is, I did not see any evidence that your device has the capability to produce pdf by its own (other device works the same way)

**Comment by hendrik1120** [comment]
I mean it can and it does even directly from the webui with live preview, but I guess the solution works also.
<img width="1401" alt="webui" src="https://user-images.githubusercontent.com/89412959/197365193-74020937-65be-4849-bd61-a55f6450c503.png">

**Comment by manuc66** [comment]
Here are you device scan capabilites:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- THIS DATA SUBJECT TO DISCLAIMER(S) INCLUDED WITH THE PRODUCT OF ORIGIN. -->
<ScanCaps xmlns="http://www.hp.com/schemas/imaging/con/cnx/scan/2008/08/19">
	<DeviceCaps>
		<ModelName>xxxx</ModelName>
		<DerivativeNumber>8</DerivativeNumber>
	</DeviceCaps>
	<ColorEntries>
		<ColorEntry>
			<ColorType>K1</ColorType>
			<Formats>
				<Format>Raw</Format>
			</Formats>
			<ImageTransforms>
				<ImageTransform>ToneMap</ImageTransform>
				<ImageTransform>Sharpening</ImageTransform>
				<ImageTransform>NoiseRemoval</ImageTransform>
			</ImageTransforms>
			<GrayRenderings>
				<GrayRendering>GrayCcdEmulated</GrayRendering>
			</GrayRenderings>
		</ColorEntry>
		<ColorEntry>
			<ColorType>Gray8</ColorType>
			<Formats>
				<Format>Raw</Format>
				<Format>Jpeg</Format>
			</Formats>
			<ImageTransforms>
				<ImageTransform>ToneMap</ImageTransform>
				<ImageTransform>Sharpening</ImageTransform>
				<ImageTransform>NoiseRemoval</ImageTransform>
			</ImageTransforms>
			<GrayRenderings>
				<GrayRendering>NTSC</GrayRendering>
				<GrayRendering>GrayCcdEmulated</GrayRendering>
			</GrayRenderings>
		</ColorEntry>
		<ColorEntry>
			<ColorType>Color8</ColorType>
			<Formats>
				<Format>Raw</Format>
				<Format>Jpeg</Format>
			</Formats>
			<ImageTransforms>
				<ImageTransform>ToneMap</ImageTransform>
				<ImageTransform>Sharpening</ImageTransform>
				<ImageTransform>NoiseRemoval</ImageTransform>
			</ImageTransforms>
		</ColorEntry>
	</ColorEntries>
	<Platen>
		<InputSourceCaps>
			<MinWidth>8</MinWidth>
			<MinHeight>8</MinHeight>
			<MaxWidth>2550</MaxWidth>
			<MaxHeight>3508</MaxHeight>
			<RiskyLeftMargin>34</RiskyLeftMargin>
			<RiskyRightMargin>33</RiskyRightMargin>
			<RiskyTopMargin>34</RiskyTopMargin>
			<RiskyBottomMargin>46</RiskyBottomMargin>
			<MinResolution>75</MinResolution>
			<MaxOpticalXResolution>1200</MaxOpticalXResolution>
			<MaxOpticalYResolution>2400</MaxOpticalYResolution>
			<SupportedResolutions>
				<Resolution>
					<XResolution>75</XResolution>
					<YResolution>75</YResolution>
					<NumCcd>1</NumCcd>
					<ColorTypes>
						<ColorType>K1</ColorType>
						<ColorType>Gray8</ColorType>
						<ColorType>Color8</ColorType>
					</ColorTypes>
				</Resolution>
				<Resolution>
					<XResolution>100</XResolution>
					<YResolution>100</YResolution>
					<NumCcd>1</NumCcd>
					<ColorTypes>
						<ColorType>K1</ColorType>
						<ColorType>Gray8</ColorType>
						<ColorType>Color8</ColorType>
					</ColorTypes>
				</Resolution>
				<Resolution>
					<XResolution>200</XResolution>
					<YResolution>200</YResolution>
					<NumCcd>1</NumCcd>
					<ColorTypes>
						<ColorType>K1</ColorType>
						<ColorType>Gray8</ColorType>
						<ColorType>Color8</ColorType>
					</ColorTypes>
				</Resolution>
				<Resolution>
					<XResolution>300</XResolution>
					<YResolution>300</YResolution>
					<NumCcd>1</NumCcd>
					<ColorTypes>
						<ColorType>K1</ColorType>
						<ColorType>Gray8</ColorType>
						<ColorType>Color8</ColorType>
					</ColorTypes>
				</Resolution>
				<Resolution>
					<XResolution>600</XResolution>
					<YResolution>600</YResolution>
					<NumCcd>1</NumCcd>
					<ColorTypes>
						<ColorType>K1</ColorType>
						<ColorType>Gray8</ColorType>
						<ColorType>Color8</ColorType>
					</ColorTypes>
				</Resolution>
				<Resolution>
					<XResolution>1200</XResolution>
					<YResolution>1200</YResolution>
					<NumCcd>1</NumCcd>
					<ColorTypes>
						<ColorType>K1</ColorType>
						<ColorType>Gray8</ColorType>
						<ColorType>Color8</ColorType>
					</ColorTypes>
				</Resolution>
				<Resolution>
					<XResolution>1200</XResolution>
					<YResolution>2400</YResolution>
					<NumCcd>1</NumCcd>
					<ColorTypes>
						<ColorType>K1</ColorType>
						<ColorType>Gray8</ColorType>
						<ColorType>Color8</ColorType>
					</ColorTypes>
				</Resolution>
				<Resolution>
					<XResolution>1200</XResolution>
					<YResolution>4800</YResolution>
					<NumCcd>1</NumCcd>
					<ColorTypes>
						<ColorType>K1</ColorType>
						<ColorType>Gray8</ColorType>
						<ColorType>Color8</ColorType>
					</ColorTypes>
				</Resolution>
			</SupportedResolutions>
		</InputSourceCaps>
	</Platen>
</ScanCaps>
```

**Comment by manuc66** [comment]
But I agree that through eSCL printers do render pdf not images

See:
https://192.168.5.221/Scan/ScanCaps (this project use this)
vs
https://192.168.5.221/eSCL/ScannerCapabilities

**Comment by hendrik1120** [comment]
Yeah ok, I was just wondering. The package you are using to generate pdf from jpeg is probably more efficient and cleaner than any hardware acceleration in this old printer :D But I pass it into Paperless-ngx anyway, so it really doesn't matter that much.
Printers are just evil...
