### ISSUE TITLE
Autoscan

### ISSUE THREAD

**Issue by lordbagel42** [manuc66/node-hp-scan-to#610]
**Is your feature request related to a problem? Please describe.**

No

**Describe the solution you'd like**

Basically, a system where the software watches to see if the printer has any paper loaded in the ADF, and if so, scans it, and then sends it to Paperless.

**Describe alternatives you've considered**

Writing this myself when I have no idea how.

**Additional context**

HP sucks and while I would prefer to just get something that works, this is the best possible until then.

**Comment by lordbagel42** [comment]
This could be done by monitoring the status of the ADF, and if it registers as loaded, trigger a scan.

**Comment by manuc66** [comment]
Hi,

Currently the tool monitor only /EventMgmt/EventTable which does not contain that information

By polling /Scan/Status could be used to monitor the ADF state

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- THIS DATA SUBJECT TO DISCLAIMER(S) INCLUDED WITH THE PRODUCT OF ORIGIN. -->
<ScanStatus xmlns="http://www.hp.com/schemas/imaging/con/cnx/scan/2008/08/19">
	<ScannerState>Idle</ScannerState>
	<AdfState>Empty</AdfState>
</ScanStatus>
```

```xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- THIS DATA SUBJECT TO DISCLAIMER(S) INCLUDED WITH THE PRODUCT OF ORIGIN. -->
<ScanStatus xmlns="http://www.hp.com/schemas/imaging/con/cnx/scan/2008/08/19">
	<ScannerState>Idle</ScannerState>
	<AdfState>Loaded</AdfState>
</ScanStatus>
```

I think it could be a bit risky for the device to not wait an acknowledgment of the user because it would eat the paper without notice. The 'risk' could be mitigated by only starting the scan once the paper is there for some defined safe time period.

**Comment by autumnwalker** [comment]
hmm ... I think this started doing autoscan in the :latest docker. I was trying to figure out what is wrong with my printer after latest update and then found this.

**Comment by manuc66** [comment]
@autumnwalker I'm sorry for this, it should be fixed now since I merged some PR, but I'll have to find a fix to avoid feature branch to be published on the 'latest' tag

The best yes is to consume master indeed

Sorry again for the inconvenience

**Comment by autumnwalker** [comment]
> @autumnwalker I'm sorry for this, it should be fixed now since I merged some PR, but I'll have to find a fix to avoid feature branch to be published on the 'latest' tag
> 
> The best yes is to consume master indeed
> 
> Sorry again for the inconvenience

No problem at all! Glad it was a simple fix / easy to catch.

**Comment by autumnwalker** [comment]
Switched from :master to :latest to resolve the /tmp issue and autoscan seems to have come back. Is there a way to disable the feature in :latest?

**Comment by autumnwalker** [comment]
That must have been it. I forced an update and it is working fine now. Apologies for the false alarm!
