### ISSUE TITLE
Scanned files not being moved to target directory (npx)

### ISSUE THREAD

**Issue by davearias** [manuc66/node-hp-scan-to#647]
**Describe the bug**
Device: HP Officejet Pro 7720

Command line or Docker :
npx node-hp-scan-to@latest -ip 192.168.10.50 -l scan-to-paperless -d /var/scan

Describe what is happening
After files are scanned, they are moved to a second /tmp directory, instead of the specified target directory. npx reports it is installing v1.3.0, I have cleared npx cache as well.

I assume this is similar to  [664](https://github.com/manuc66/node-hp-scan-to/issues/644#issue-1635433819)?

Please attach the output with debug (-D switch, see documentation)
[node-hp-scan-to_debug.txt](https://github.com/manuc66/node-hp-scan-to/files/11053219/node-hp-scan-to_debug.txt)

**Comment by manuc66** [comment]
@davearias It should be ok in version 1.3.1

**Comment by davearias** [comment]
Excellent! I wasn’t sure exactly how npm works with this. I appreciate the
fix and the time spent on this great project!

**Comment by davearias** [comment]
Confirmed, works perfectly!
