### ISSUE TITLE
The project description

### ISSUE THREAD

**Issue by Ashark** [manuc66/node-hp-scan-to#673]
Hi. I came here from arch linux, searched scanning utility for linux and found node-hp-scan-to package: https://aur.archlinux.org/packages/node-hp-scan-to

I read readme, but it is not clear what this project is. It is not related to hp-scan utility, right? It is said that it is made by reverse engineer the windows app. What exactly app? Can you please describe that in readme?

**Comment by kalipso-cyber** [comment]
As far as I understand (just installing it right now, so I might have misunderstood the README), this tool is designed to allow you to scan from an HP All-in-One printer/scanner to your computer. I expect it is similar to the HP Scan utility in its core functionality - enabling a "receiving end"/client on the host for the HP AIO device to scan to. And I believe it does little more than that, whereas I'm assuming the HP Scan utility offers a bunch of additional features.

My use case for it is to run it on an LXC container which also hosts an instance of [paperless-ngx](https://github.com/paperless-ngx/paperless-ngx), allowing me to send the scans from my HP AIO device to the LXC, where it will be processed by paperless-ngx.

Again, this is only my current understanding and I haven't actually installed the tool yet. Should it not provide the functionality described above, I'll make sure to comment here.

**Comment by manuc66** [comment]
Hello,

This project reverse engineered what's happening behind the scene when you use this application on Windows 
![image](https://github.com/manuc66/node-hp-scan-to/assets/5827164/63781777-390d-4eb8-bec0-7c3c767ef1d4)

It relates to the feature described in this page https://www.solveyourtech.com/how-to-scan-to-computer-from-the-photosmart-6510/

Being a Node.js app, it has been developed to run on Linux & Docker, but it also works on Windows and I would expect it works on many more operating systems...

Many people are using this app with paperless-ngx, see : https://www.reddit.com/r/selfhosted/comments/x2nnxu/paperless_ngx_nodehpscanto/

Feel free to open a pull request or provide a description that would have helped you better understand. 

Best regards
