### ISSUE TITLE
Multiple Scanners/Printers

### ISSUE THREAD

**Issue by Dvalin21** [manuc66/node-hp-scan-to#695]
Would like to be able to use multiple scanners and printers at one time!!

**Comment by manuc66** [comment]
Hi @Dvalin21 

What's the issue for you to spin multiple instance with different configurations ?

**Comment by Dvalin21** [comment]
> Hi @Dvalin21
> 
> What's the issue for you to spin multiple instance with different configurations ?

I didn't think about just installing it multiple times and using the ip address for each printer
