### ISSUE TITLE
Upload directly topaperless-ngx

### ISSUE THREAD

**Issue by manuc66** [manuc66/node-hp-scan-to#760]
Here is the API that might be used :
https://docs.paperless-ngx.com/api/#file-uploads

**Comment by esackbauer** [comment]
Is that really needed? I just set the volume for the scan directory to paperless' inbound directory, that works fine if both paperless and node-hp-scan-to are running on the same docker host. Should work also with network mounted volumes.

**Comment by Dvalin21** [comment]
Having issue with this as paperless ngx is saying permission denied scanning directly to the "consume" folder which is monitored by Paperless ngx. And just so to add to the list of working printers HP Officeject Pro 8020 MFP

**Comment by Killom** [comment]
> Having issue with this as paperless ngx is saying permission denied scanning directly to the "consume" folder which is monitored by Paperless ngx

Presumably file permission. node-hp-scan-to is running as another user?

> Is that really needed? I just set the docker volume for the scan directory to paperless' inbound directory,

When the scans will be handed over API, there might be less permission issues. And no need to run on same host, or be able to access file shares.

Would also endorse for paperless API support

**Comment by manuc66** [comment]
done :)
