### ISSUE TITLE
Add Support for Photosmart C410b

### ISSUE THREAD

**Issue by ThomasCr** [manuc66/node-hp-scan-to#795]
My Photosmart C410b has no scan destinations, which can be set.
But I know, that it is possible, to scan over network/remote from the printer
Also scanning from linux with HPLIP addon is possible.

It would be nice, if this project can also support this those printers.

**Comment by manuc66** [comment]
Hello @ThomasCr 

Can you send the logs of the application in debug, it will capture some of its capabilities through the printer API.

If you can manage to get the unencrypted network traffic between the device and the official ScanToComputer it may help as well 

Depending on the device capabilities and API involved it may be possible & reasonable to extend this piece of software to make it compatible.

**Comment by manuc66** [comment]
Without more details it's impossible to take care of this printer
