### ISSUE TITLE
Add healthcheck in Dockerfile or document it in the compose.yml

### ISSUE THREAD

**Issue by 3DJupp** [manuc66/node-hp-scan-to#967]
Would it be possible to have a health check in place?
Either something thats listening on a certain port:
`HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 CMD curl -f http://localhost:3000/health || exit 1`
Or answering a CMD/CMD-SHELL:
`HEALTHCHECK --interval=30s --timeout=10s --start-period=5s --retries=3 CMD node /app/healthcheck.js`

Thanks for this great project, I like it :heart:

**Comment by manuc66** [comment]
Hi @3DJupp 

Would you consider that it's healthy if the printer is not reachable ?

**Comment by manuc66** [comment]
Implementend with basic support
