### ISSUE TITLE
RFE please document how to clear-registrations with public pre-built Docker image:

### ISSUE THREAD

**Issue by pcfe** [manuc66/node-hp-scan-to#994]
**Is your feature request related to a problem? Please describe.**
Can you please add the `docker exec -it […]` invocation needed to clear-registrations to the main README.md?

**Describe the solution you'd like**
After initial playing, I'd like to clear a previously registered test name from the printer's _Scan to Computer_ list using the Docker container. But
```bash
docker exec -it node-hp-scan-to npx node-hp-scan-to clear-registrations --help 
```
gives me
```                                                                                                                                                                                    
sh: node-hp-scan-to: not found
```

**Describe alternatives you've considered**
Doing a clean _power cycle_ of the printer (FWIW while the container was stopped) did remove the previously registered test name from the printer's _Scan to Computer_ list.

**Additional context**
none comes to mind, ask if unclear.

**Comment by manuc66** [comment]
Hi @pcfe 

The npx is to run without docker image, directly from the npm package

If you want to run it from the docker image you can do this:

```
docker exec -it c875dad39abb node index.js --help
```
